module.exports = [
  'Électronique',
  'Téléphones',
  'Ordinateurs',
  'Accessoires',
  'Mode Femme',
  'Mode Homme',
  'Chaussures',
  'Montres & Bijoux',
  'Meubles',
  'Maison & Déco',
  'Électroménager',
  'Jeux & Consoles',
  'Livres',
  'Sport & Loisirs',
  'Santé & Beauté',
  'Bébés & Enfants',
  'Informatique',
  'Instruments de musique',
  'Véhicules',
  'Pièces & Accessoires auto',
  'Immobilier',
  'Services',
  'Animaux',
  'Autres',
];
